### ISSUE TITLE
Actuator Disk TODO's

### ISSUE THREAD

**Issue by psakievich** [Exawind/amr-wind#634]
- [x]  Remove density as an actuator specific input #640 
- [x] Default num_blades to 3 for Joukowksy #635
- [x] Consolidate syntax for `num_points_r` #635
- [x] Input as TSR or RPM instead of omega #645 
- [x] Output TSR in ncfile #635
- [ ] Make it work with mesh mapping #647 
- [ ] Create file reads for the table of look up quantities
- [x] Add `f_theta` and `f_z` output to ncfile #635
- [x] Add a "reasonable" default for `vortex_core_size` (Maybe 10-15% of rotor diameter?) #645 
- [ ] Add a "disktype" flag to ncfile output.
- [x] Add power output to ncfile #666
- [ ] Add power calculation for UnifCtDisk (see @michaeljbrazell branch for a version of the calculation, maybe generalize it)
- [ ] Add time-history of turbine yaw output to ncfile (c.f. yaw controller changes from HFM Q4)

**Comment by lawrenceccheung** [comment]
@neilmatula and I are realizing that the `actuator_src_term[x,y]` output is dependent on mesh resolution, which makes it hard to compare against literature.  So I added `f_theta` and `f_z` output to this list to help with validation.

Lawrence

**Comment by lawrenceccheung** [comment]
Sorry, adding one more minor thing to the list.  Since it seems like `vortex_core_size` has an impact on the comparisons (at least with Sorensen's cases), we should probably give it a reasonable value to start with if people don't have any idea what it should be.

Lawrence

**Comment by lawrenceccheung** [comment]
And one more minor thing while I'm thinking about it.  Was just thinking it would be handy to include a `diskType` flag to the ncfile to indicate whether it's a `UniformCtDisk` or `JoukowskyDisk` type.  Just a minor convenience thing, but I might use it in the postprocessing scripts so I can tell whether to expect things like TSR output or not.

Lawrence

**Comment by psakievich** [comment]
@neilmatula and @ndevelder can you update anything you've done on this issue?

**Comment by neilmatula** [comment]
@psakievich 
Done!
I checked the Input TSR and vortex_core_size boxes.

**Comment by marchdf** [comment]
@psakievich, @neilmatula, @lawrenceccheung  do we still need to keep this open? I see a bunch has been done already.
